apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
      - name: library-api
        image: himasai1423/api-lib-front:v2.0 
        ports:
        - containerPort: 3000
        env:
        - name: DB_URI
          value: "mongodb://mongo-service:27017" 
      
      - name: mongo
        image: mongo:7.0-rc
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: my-mongo-data
